FROM python:3.10-slim

WORKDIR /app

COPY requirements.txt .  

RUN python -m pip install --upgrade pip \
    && pip install --retries 10 -r requirements.txt

COPY app/ ./app/

CMD ["uvicorn", "app.main:app", "--host", "0.0.0.0", "--port", "9000"]

